import type { Metadata } from "next";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import VisualEditingComponent from "@/components/VisualEditing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();
  
  return (
    <html lang="en">
      <body>
        {children}
        {isEnabled && <VisualEditingComponent />}
        <SanityLive />
      </body>
    </html>
  );
}
